# Generated by Django 5.2.14 on 2026-09-09 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_number', models.IntegerField()),
                ('name', models.CharField(max_length=64)),
                ('map_width', models.FloatField(default=100.0)),
                ('map_height', models.FloatField(default=100.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='navigation.building')),
            ],
            options={
                'ordering': ['floor_number'],
                'unique_together': {('building', 'floor_number')},
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('block', models.CharField(default='1', max_length=32)),
                ('name', models.CharField(max_length=128)),
                ('type', models.CharField(choices=[('entrance', 'Entrance'), ('room', 'Room'), ('junction', 'Junction'), ('corridor', 'Corridor'), ('stair', 'Staircase'), ('lift', 'Lift'), ('amenity', 'Amenity'), ('office', 'Office'), ('lab', 'Lab'), ('restroom', 'Restroom')], default='room', max_length=32)),
                ('x', models.FloatField(help_text='X coordinate on floor plan (0-100 or pixels)')),
                ('y', models.FloatField(help_text='Y coordinate on floor plan (0-100 or pixels)')),
                ('qr_code', models.CharField(db_index=True, max_length=128, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_checkpoint', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='navigation.building')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='navigation.floor')),
            ],
            options={
                'ordering': ['floor__floor_number', 'node_id'],
            },
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField(help_text='Distance in metres or coordinate units')),
                ('accessible', models.BooleanField(default=True, help_text='True if wheelchair accessible')),
                ('movement_type', models.CharField(choices=[('walk', 'Walk'), ('stairs', 'Stairs'), ('lift', 'Lift')], default='walk', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='navigation.node')),
                ('to_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='navigation.node')),
            ],
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.CharField(max_length=255, unique=True)),
                ('image_path', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_detail', to='navigation.node')),
            ],
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['node_id'], name='navigation__node_id_c5e790_idx'),
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['qr_code'], name='navigation__qr_code_f3e6c6_idx'),
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['floor', 'type'], name='navigation__floor_i_d521a2_idx'),
        ),
        migrations.AddIndex(
            model_name='edge',
            index=models.Index(fields=['from_node', 'is_active'], name='navigation__from_no_e66f50_idx'),
        ),
        migrations.AddIndex(
            model_name='edge',
            index=models.Index(fields=['to_node', 'is_active'], name='navigation__to_node_5a91a2_idx'),
        ),
        migrations.AddIndex(
            model_name='edge',
            index=models.Index(fields=['movement_type'], name='navigation__movemen_35945c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='edge',
            unique_together={('from_node', 'to_node', 'movement_type')},
        ),
    ]
