# Generated by Django 5.2.14 on 2026-09-10 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='building',
            name='category',
            field=models.CharField(choices=[('academic', 'Academic Block'), ('facility', 'Facility'), ('administration', 'Administration'), ('hostel', 'Hostel'), ('gate', 'Campus Gate'), ('landmark', 'Landmark'), ('other', 'Other')], default='academic', max_length=32),
        ),
        migrations.AddField(
            model_name='building',
            name='entrance_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='entrance_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='building',
            name='is_navigable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='building',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BuildingEntrance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrance_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(default='Main Entrance', max_length=128)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('outdoor_node_id', models.CharField(blank=True, default='', max_length=64)),
                ('indoor_node_id', models.CharField(blank=True, default='', max_length=64)),
                ('is_accessible', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrances', to='navigation.building')),
            ],
        ),
        migrations.CreateModel(
            name='OutdoorNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('type', models.CharField(choices=[('gate', 'Campus Gate'), ('junction', 'Path Junction'), ('walkway', 'Walkway Point'), ('building_entrance', 'Building Entrance'), ('facility', 'Facility'), ('landmark', 'Landmark')], default='walkway', max_length=32)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_checkpoint', models.BooleanField(default=False)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outdoor_nodes', to='navigation.building')),
            ],
            options={
                'ordering': ['node_id'],
            },
        ),
        migrations.CreateModel(
            name='OutdoorEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_m', models.FloatField(help_text='Distance in metres')),
                ('accessible', models.BooleanField(default=True)),
                ('movement_type', models.CharField(choices=[('walk', 'Walk'), ('accessible_walk', 'Accessible Walk')], default='walk', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('from_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='navigation.outdoornode')),
                ('to_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='navigation.outdoornode')),
            ],
            options={
                'unique_together': {('from_node', 'to_node', 'movement_type')},
            },
        ),
    ]
