# Generated by Django 5.2.14 on 2026-09-10 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0002_alter_building_options_building_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('space_type', models.CharField(default='other', max_length=32)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='building',
            name='coordinate_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='building',
            name='source',
            field=models.CharField(choices=[('verified', 'Verified'), ('official', 'Official document'), ('synthetic', 'Synthetic placeholder'), ('unknown', 'Unknown')], default='unknown', max_length=16),
        ),
        migrations.AddField(
            model_name='buildingentrance',
            name='source',
            field=models.CharField(default='unknown', max_length=16),
        ),
        migrations.AddField(
            model_name='outdooredge',
            name='edge_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='outdoornode',
            name='coordinate_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='outdoornode',
            name='is_accessible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='outdoornode',
            name='source',
            field=models.CharField(default='unknown', max_length=16),
        ),
        migrations.CreateModel(
            name='CampusFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('category', models.CharField(default='facility', max_length=32)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(default='unknown', max_length=16)),
                ('coordinate_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facilities', to='navigation.building')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
