# Generated by Django 5.2.14 on 2026-09-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0003_campusspace_building_coordinate_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outdoornode',
            name='qr_code',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True, unique=True),
        ),
    ]
