# Generated by Django 5.2.14 on 2026-09-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0004_outdoornode_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='edge',
            name='edge_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='floor',
            name='map_asset',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='node',
            name='type',
            field=models.CharField(choices=[('entrance', 'Entrance'), ('room', 'Room'), ('door', 'Door'), ('junction', 'Junction'), ('corridor', 'Corridor'), ('stair', 'Staircase'), ('lift', 'Lift'), ('amenity', 'Amenity'), ('office', 'Office'), ('lab', 'Lab'), ('hall', 'Hall'), ('restroom', 'Restroom'), ('facility', 'Facility')], default='room', max_length=32),
        ),
    ]
